### ISSUE TITLE
Is ax instruction 2 or 3?

### ISSUE THREAD

**Issue by bshanks** [mnemnion/ax#1]
In https://github.com/mnemnion/ax/blob/master/ax%20spec.md, the 'Axioms' and the 'Terms' sections seem to disagree on whether 2 is ax and 3 is br, or 2 is br and 3 is ax:

Axioms
...
Ξ [a 2 0]        →   ?
Ξ [a 2 1]        →   a
Ξ [[a b] 2 2]    →   a
Ξ [[a b] 2 3]    →   b
Ξ [a 2 (b + b)]      →   Ξ [Ξ [a 2 b] 2 2]
Ξ [a 2 (b + b + 1)]  →   Ξ [Ξ [a 2 b] 2 3]
Ξ [n 2 b]        →   Ξ [n]
Ξ [3 3 [[2 1] [1 2 1]] [0 2 1]]   →   [3 4]
...
Ξ [a 3 b c]      →   Ξ [Ξ [a b] Ξ [a c]]
...
Terms

7 operators
0  := is
1  := inc
2  := ax
3  := br
4  := eq
5  := fz
6  := cel

**Comment by mnemnion** [comment]
Right you are. The terms were incorrect. Thanks!
